<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         DebugKit 0.1
 * @license       https://www.opensource.org/licenses/mit-license.php MIT License
 */
/**
 * @var \DebugKit\View\AjaxView $this
 * @var string $error
 * @var bool|null $sort
 * @var array $variables
 * @var array $errors
 */
?>
<style type="text/css">
    .ai-button {
        height:30px;
        background-color: #d43c43;
        color: white;
        font-weight: bold;
        border: #d43c43;
    }
    .grey-bg {
        background-color: lightgrey;
        padding: 10px;
        border-radius: 10px;
    }
</style>
<div class="c-ai-panel">
    <div class="debugkit-help">
        <h3>⚠️ Important: API Key &amp; Data Usage</h3>
        <p>Before using the AI Help features, please read the following:</p>
        <ul>
            <li><strong>Potential Costs:</strong> Requesting help with an API key from a paid service (like Google Cloud Vertex AI) <strong>will incur charges</strong> based on your provider's pricing. You are responsible for any costs generated by your API key.</li>
            <li><strong>Get a Free API Key:</strong> For development, you can get a free API key from <strong><a href="https://aistudio.google.com/" target="_blank" rel="noopener noreferrer">Google AI Studio</a></strong>. This key comes with a generous free daily quota that is perfect for testing and development.</li>
            <li><strong>Data Privacy Notice:</strong> Please be aware that when using a free API key from Google AI Studio, the data you send (your code, queries, logs, etc.) may be used by Google to improve its models. <strong>Do not send sensitive or production data.</strong></li>
        </ul>

        <hr>

        <h3>DebugKit Help</h3>
        <p>This tool acts as an AI-powered expert that analyzes your application's backend performance and structure for the current request.</p>
        <p><strong>What Data Is Sent?</strong> 🕵️‍♀️</p>
        <p>When you request help, the <strong>content of all DebugKit panels</strong> is sent for analysis. This includes your database queries, request headers, application logs, timers, and environment variables.</p>
        <p><strong>What Help Do You Get?</strong> 💡</p>
        <p>You'll receive a detailed report with suggestions to:</p>
        <ul>
            <li>Optimize slow database queries and fix <strong>N+1 problems</strong>.</li>
            <li>Identify performance <strong>bottlenecks</strong> in your code.</li>
            <li>Improve adherence to <strong>CakePHP conventions</strong> and best practices.</li>
            <li>Get clearer explanations for errors and warnings found in your logs.</li>
        </ul>
        <br />
        <?php if (\Cake\Core\Configure::read('DebugKit.AI.apiKey')) : ?>
            <?= $this->Form->button(__('Send request to AI agent'), ['data-action' => 'debug-kit-help', 'class' => 'btn btn-success ai-button']) ?>
            <div class="help-result">
                <?= $this->Html->image('CakeDC/DebugKitAI.loading.gif', ['class' =>'loading', 'style' => 'display: none; width: 100px; height: 100px']); ?>
            </div>
        <?php else: ?>
            <strong><?= __('API Key for AI Agent has not been configured properly') ?></strong>
        <?php endif; ?>

    </div>

    <hr>

    <div class="html-help">
        <h3>HTML Help</h3>
        <p>This tool reviews the rendered front-end code of your page, focusing on structure, accessibility, and CakePHP template practices.</p>
        <p><strong>What Data Is Sent?</strong> 📄</p>
        <p>When you request help, the <strong>complete HTML source code</strong> of the page you are currently viewing is sent for analysis.</p>
        <p><strong>What Help Do You Get?</strong> ✨</p>
        <p>You'll receive actionable feedback to:</p>
        <ul>
            <li>Improve <strong>semantic HTML structure</strong> and on-page <strong>SEO</strong> elements.</li>
            <li>Fix <strong>accessibility (A11Y)</strong> issues like missing <code>alt</code> attributes or incorrect form labels.</li>
            <li>Replace hardcoded HTML with dynamic, maintainable code using CakePHP's <strong><code>HtmlHelper</code></strong> and <strong><code>FormHelper</code></strong>.</li>
        </ul>
        <br />
        <?php if (\Cake\Core\Configure::read('DebugKit.AI.apiKey')) : ?>
            <?= $this->Form->button(__('Send HTML to AI agent'), ['data-action' => 'html-help', 'class' => 'btn btn-success ai-button']) ?>
            <div class="help-result">
                <?= $this->Html->image('CakeDC/DebugKitAI.loading.gif', ['class' =>'loading', 'style' => 'display: none; width: 100px; height: 100px']); ?>
            </div>
        <?php else: ?>
            <strong><?= __('API Key for AI Agent has not been configured properly') ?></strong>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ai-button').on('click', function() {
            let $this = $(this);
            $(this).hide();
            $(this).parent().find('.help-result .loading').show();
            const action = $(this).data('action');
            $.get('/debug-kit-ai/requests/' + action, function(response) {
                $this.parent().find('.help-result').html(response).addClass('grey-bg');
            })
        });
    })
</script>
